Repository ooyala/skin-config, pull requests merged in 2018-04, with the labels that each got.

#199 [bugfix/PLAYER-3316] Remove default audio parameter
  skin.json
Labels: blocker, bug

#204 [PLAYER-3390] Restored audio field to skin.json
  skin.json
Labels: blocker

#203 [bugfix/PLAYER-634] Add constants for error messages
  languageFiles/en.json
  languageFiles/es.json
  languageFiles/ja.json
  languageFiles/ko.json
  languageFiles/zh.json
Labels: bug
